# Share version definition for both Rust and Python-pyo3 packages
[workspace]
members = ["rust", "python-pyo3"]
resolver = "3"

[workspace.package]
edition = "2024"
version = "2.7.6"
rust-version = "1.90"

[profile.release]
lto = "thin"
